# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode
name: $(Build.BuildId)

variables:
  FLUTTER_CACHE_FOLDER: $(Pipeline.Workspace)/../hostedtoolcache/Flutter


jobs:
  - job: Android Build Validation
    pool:
      vmImage: 'macOS-latest'
        
    steps:
    
    - task: FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'latest'
    
    - task: FlutterBuild@0
      inputs:
        target: 'apk'
        projectDirectory: '.'
        entryPoint: 'lib/main.dart'
        flutterDirectory: './Users/runner/work'
        apkTargetPlatform: 'android-arm64'
